#<% require 'kitchen-sync' %>
---
driver:
  name: vagrant
  require_chef_omnibus: 12.3.0

provisioner:
  name: chef_zero
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus
  attributes:
    authorization:
      sudo:
        users: [vagrant]

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[cafe-core::default]

  - name: sudo
    run_list:
      - recipe[cafe-core::sudo]
